# generated by datamodel-codegen:
#   filename:  user-service.json
#   timestamp: 2026-07-19T18:18:12+00:00

from __future__ import annotations

from dataclasses import dataclass

from python.libs.entities.user import Gender


@dataclass
class CreateUserBody:
    name: str
    gender: Gender
    age: int | None = None
    short_bio: str | None = ''
    favorite_categories: list[str] | None = None
    city_id: int | None = None
    birthdate: str | None = None
    auth_account_id: int | None = None


@dataclass
class UpdateBioBody:
    long_bio: str


@dataclass
class UpdateProfileBody:
    name: str | None = None
    favorite_categories: list[str] | None = None


@dataclass
class UserOut:
    id: int
    name: str
    status: str
    gender: Gender = Gender.MALE
    short_bio: str | None = ''
    long_bio: str | None = ''
    age: int | None = None
    avatar_url: str | None = None
    role: str | None = 'REGULAR'
    favorite_categories: list[str] | None = None
    onboarding_completed: bool | None = False
    deleted: bool | None = False
    city_id: int | None = None
    birthdate: str | None = None
    auth_account_id: int | None = None


@dataclass
class ValidationError:
    loc: list[str | int]
    msg: str
    type: str


@dataclass
class AvatarUploadOut:
    avatar_url: str
    user: UserOut


@dataclass
class HTTPValidationError:
    detail: list[ValidationError] | None = None
