-- Справочник категорий товаров и услуг.
INSERT INTO product_categories (code, title, title_en, sort_order) VALUES
    ('food', 'Еда', 'Food', 10),
    ('ready_meals', 'Готовая еда', 'Ready meals', 20),
    ('bakery_goods', 'Выпечка', 'Bakery', 30),
    ('coffee', 'Кофе', 'Coffee', 40),
    ('drinks', 'Напитки', 'Drinks', 50),
    ('grocery', 'Продукты', 'Grocery', 60),
    ('concert', 'Концерт', 'Concert', 70),
    ('theater_ticket', 'Билет в театр', 'Theater ticket', 80),
    ('cinema_ticket', 'Билет в кино', 'Cinema ticket', 90),
    ('exhibition_ticket', 'Билет на выставку', 'Exhibition ticket', 100),
    ('standup', 'Стендап', 'Stand-up', 110),
    ('festival', 'Фестиваль', 'Festival', 120),
    ('membership', 'Абонемент', 'Membership', 130),
    ('yoga_class', 'Занятие йогой', 'Yoga class', 140),
    ('fitness_class', 'Фитнес-занятие', 'Fitness class', 150),
    ('dance_class', 'Танцевальное занятие', 'Dance class', 160),
    ('workshop_session', 'Мастер-класс', 'Workshop', 170),
    ('kids_class', 'Детское занятие', 'Kids class', 180),
    ('beauty', 'Красота', 'Beauty', 190),
    ('haircut', 'Стрижка', 'Haircut', 200),
    ('manicure', 'Маникюр', 'Manicure', 210),
    ('spa_treatment', 'SPA-процедура', 'SPA treatment', 220),
    ('cosmetics', 'Косметика', 'Cosmetics', 230),
    ('sport_goods', 'Спортивные товары', 'Sport goods', 240),
    ('sport_rental', 'Прокат спорта', 'Sport rental', 250),
    ('personal_training', 'Персональная тренировка', 'Personal training', 260),
    ('construction', 'Строительные товары', 'Construction goods', 270),
    ('tools', 'Инструменты', 'Tools', 280),
    ('finishing_materials', 'Отделочные материалы', 'Finishing materials', 290),
    ('plumbing', 'Сантехника', 'Plumbing', 300),
    ('electrical', 'Электрика', 'Electrical', 310),
    ('furniture', 'Мебель', 'Furniture', 320),
    ('home_goods', 'Товары для дома', 'Home goods', 330),
    ('clothes', 'Одежда', 'Clothes', 340),
    ('shoes', 'Обувь', 'Shoes', 350),
    ('accessories', 'Аксессуары', 'Accessories', 360),
    ('delivery', 'Доставка', 'Delivery', 370),
    ('repair', 'Ремонт', 'Repair', 380),
    ('cleaning', 'Клининг', 'Cleaning', 390),
    ('photo_session', 'Фотосессия', 'Photo session', 400),
    ('massage', 'Массаж', 'Massage', 410),
    ('education', 'Обучение', 'Education', 420),
    ('auto_service', 'Автосервис', 'Auto service', 430),
    ('pet_service', 'Услуги для питомцев', 'Pet service', 440),
    ('flowers', 'Цветы', 'Flowers', 450),
    ('books', 'Книги', 'Books', 460),
    ('electronics', 'Электроника', 'Electronics', 470),
    ('gifts', 'Подарки', 'Gifts', 480)
ON CONFLICT (code) DO UPDATE SET
    title = EXCLUDED.title,
    title_en = EXCLUDED.title_en,
    sort_order = EXCLUDED.sort_order,
    updated_at = NOW();
